# Copyright (C) 2013 Sony Mobile Communication
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#### THE FILE IS GENERATED BY SCRIPT SO DO NOT MODIFY IT MANUALLY! ####

PRODUCT_COPY_FILES += \
    vendor/sony/c1905/proprietary/root/sbin/wait4tad_static:root/sbin/wait4tad_static \
    vendor/sony/c1905/proprietary/root/sbin/tad_static:root/sbin/tad_static \
    vendor/sony/c1905/proprietary/lib/libCB.so:lib/libCB.so \
    vendor/sony/c1905/proprietary/lib/libchromatix_s5k4e1_2nd_default_video_1.so:lib/libchromatix_s5k4e1_2nd_default_video_1.so \
    vendor/sony/c1905/proprietary/lib/libchromatix_s5k4e1_2nd_preview.so:lib/libchromatix_s5k4e1_2nd_preview.so \
    vendor/sony/c1905/proprietary/lib/libchromatix_s5k4e1_2nd_preview_1.so:lib/libchromatix_s5k4e1_2nd_preview_1.so \
    vendor/sony/c1905/proprietary/lib/libchromatix_s5k4e1_default_video.so:lib/libchromatix_s5k4e1_default_video.so \
    vendor/sony/c1905/proprietary/lib/libchromatix_s5k4e1_default_video_1.so:lib/libchromatix_s5k4e1_default_video_1.so \
    vendor/sony/c1905/proprietary/lib/libchromatix_s5k4e1_preview.so:lib/libchromatix_s5k4e1_preview.so \
    vendor/sony/c1905/proprietary/lib/libchromatix_s5k4e1_preview_1.so:lib/libchromatix_s5k4e1_preview_1.so \
    vendor/sony/c1905/proprietary/lib/libcredential-manager-service.so:lib/libcredential-manager-service.so \
    vendor/sony/c1905/proprietary/lib/libQSEEComAPI.so:lib/libQSEEComAPI.so \
    vendor/sony/c1905/proprietary/lib/libqdi.so:lib/libqdi.so \
    vendor/sony/c1905/proprietary/lib/libsc-a3xx.so:lib/libsc-a3xx.so \
    vendor/sony/c1905/proprietary/lib/libc2d2_z180.so:lib/libc2d2_z180.so \
    vendor/sony/c1905/proprietary/lib/libmmcamera_plugin.so:lib/libmmcamera_plugin.so \
    vendor/sony/c1905/proprietary/lib/libidl.so:lib/libidl.so \
    vendor/sony/c1905/proprietary/lib/liboemcamera.so:lib/liboemcamera.so \
    vendor/sony/c1905/proprietary/lib/libtime_genoff.so:lib/libtime_genoff.so \
    vendor/sony/c1905/proprietary/lib/libtzplayready.so:lib/libtzplayready.so \
    vendor/sony/c1905/proprietary/lib/libfastcvopt.so:lib/libfastcvopt.so \
    vendor/sony/c1905/proprietary/lib/libmmcamera_faceproc.so:lib/libmmcamera_faceproc.so \
    vendor/sony/c1905/proprietary/lib/libmorpho_easy_hdr.so:lib/libmorpho_easy_hdr.so \
    vendor/sony/c1905/proprietary/lib/libqmi.so:lib/libqmi.so \
    vendor/sony/c1905/proprietary/lib/libdrmfs.so:lib/libdrmfs.so \
    vendor/sony/c1905/proprietary/lib/libimage-jpeg-enc-omx-comp.so:lib/libimage-jpeg-enc-omx-comp.so \
    vendor/sony/c1905/proprietary/lib/libqmiservices.so:lib/libqmiservices.so \
    vendor/sony/c1905/proprietary/lib/libmmcamera_3a_legacy.so:lib/libmmcamera_3a_legacy.so \
    vendor/sony/c1905/proprietary/lib/libmorpho_scene_detector.so:lib/libmorpho_scene_detector.so \
    vendor/sony/c1905/proprietary/lib/libmorpho_posture_detect.so:lib/libmorpho_posture_detect.so \
    vendor/sony/c1905/proprietary/lib/libc2d2_a3xx.so:lib/libc2d2_a3xx.so \
    vendor/sony/c1905/proprietary/lib/libdrmdiag.so:lib/libdrmdiag.so \
    vendor/sony/c1905/proprietary/lib/lib_dlb_msd.so:lib/lib_dlb_msd.so \
    vendor/sony/c1905/proprietary/lib/liblights-core.so:lib/liblights-core.so \
    vendor/sony/c1905/proprietary/lib/libsc-a2xx.so:lib/libsc-a2xx.so \
    vendor/sony/c1905/proprietary/lib/libdivxdrmdecrypt.so:lib/libdivxdrmdecrypt.so \
    vendor/sony/c1905/proprietary/lib/egl/libGLESv2_adreno200.so:lib/egl/libGLESv2_adreno200.so \
    vendor/sony/c1905/proprietary/lib/egl/libq3dtools_adreno200.so:lib/egl/libq3dtools_adreno200.so \
    vendor/sony/c1905/proprietary/lib/egl/libEGL_adreno200.so:lib/egl/libEGL_adreno200.so \
    vendor/sony/c1905/proprietary/lib/egl/eglsubAndroid.so:lib/egl/eglsubAndroid.so \
    vendor/sony/c1905/proprietary/lib/egl/libGLESv1_CM_adreno200.so:lib/egl/libGLESv1_CM_adreno200.so \
    vendor/sony/c1905/proprietary/lib/egl/libGLESv2S3D_adreno200.so:lib/egl/libGLESv2S3D_adreno200.so \
    vendor/sony/c1905/proprietary/lib/libacdbloader.so:lib/libacdbloader.so \
    vendor/sony/c1905/proprietary/lib/libprofiler_msmadc.so:lib/libprofiler_msmadc.so \
    vendor/sony/c1905/proprietary/lib/libOpenCL.so:lib/libOpenCL.so \
    vendor/sony/c1905/proprietary/lib/libmmcamera_frameproc.so:lib/libmmcamera_frameproc.so \
    vendor/sony/c1905/proprietary/lib/libdsutils.so:lib/libdsutils.so \
    vendor/sony/c1905/proprietary/lib/libqdp.so:lib/libqdp.so \
    vendor/sony/c1905/proprietary/lib/libmmcamera_image_stab.so:lib/libmmcamera_image_stab.so \
    vendor/sony/c1905/proprietary/lib/libcsd-client.so:lib/libcsd-client.so \
    vendor/sony/c1905/proprietary/lib/hw/camera.msm8960.so:lib/hw/vendor-camera.msm8960.so \
    vendor/sony/c1905/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/sony/c1905/proprietary/lib/hw/sensors.msm8960.so:lib/hw/sensors.msm8960.so \
    vendor/sony/c1905/proprietary/lib/hw/nfc.msm8960.so:lib/hw/nfc.msm8960.so \
    vendor/sony/c1905/proprietary/lib/hw/lights.msm8960.so:lib/hw/vendor-lights.default.so \
    vendor/sony/c1905/proprietary/lib/libdrmtime.so:lib/libdrmtime.so \
    vendor/sony/c1905/proprietary/lib/libI420colorconvert.so:lib/libI420colorconvert.so \
    vendor/sony/c1905/proprietary/lib/libOpenVG.so:lib/libOpenVG.so \
    vendor/sony/c1905/proprietary/lib/libqmi_client_qmux.so:lib/libqmi_client_qmux.so \
    vendor/sony/c1905/proprietary/lib/libmmcamera_interface.so:lib/libmmcamera_interface.so \
    vendor/sony/c1905/proprietary/lib/libqc-opt.so:lib/libqc-opt.so \
    vendor/sony/c1905/proprietary/lib/libqmi_encdec.so:lib/libqmi_encdec.so \
    vendor/sony/c1905/proprietary/lib/libmorpho_image_stabilizer3.so:lib/libmorpho_image_stabilizer3.so \
    vendor/sony/c1905/proprietary/lib/libmm-audio-resampler.so:lib/libmm-audio-resampler.so \
    vendor/sony/c1905/proprietary/lib/libmmcamera_tintless_wrapper.so:lib/libmmcamera_tintless_wrapper.so \
    vendor/sony/c1905/proprietary/lib/libdiag.so:lib/libdiag.so \
    vendor/sony/c1905/proprietary/lib/libqcci_legacy.so:lib/libqcci_legacy.so \
    vendor/sony/c1905/proprietary/lib/libC2D2.so:lib/libC2D2.so \
    vendor/sony/c1905/proprietary/lib/libdrmdecrypt.so:lib/libdrmdecrypt.so \
    vendor/sony/c1905/proprietary/lib/libmorpho_hdr_checker.so:lib/libmorpho_hdr_checker.so \
    vendor/sony/c1905/proprietary/lib/libmiscta.so:lib/libmiscta.so \
    vendor/sony/c1905/proprietary/lib/libmmcamera_wavelet_lib.so:lib/libmmcamera_wavelet_lib.so \
    vendor/sony/c1905/proprietary/lib/libqmi_common_so.so:lib/libqmi_common_so.so \
    vendor/sony/c1905/proprietary/lib/libqcci_adc.so:lib/libqcci_adc.so \
    vendor/sony/c1905/proprietary/lib/libmmcamera_hdr_lib.so:lib/libmmcamera_hdr_lib.so \
    vendor/sony/c1905/proprietary/lib/libmm-color-convertor.so:lib/libmm-color-convertor.so \
    vendor/sony/c1905/proprietary/lib/libgemini.so:lib/libgemini.so \
    vendor/sony/c1905/proprietary/lib/libgps.utils.so:system/lib/libgps.utils.so \
    vendor/sony/c1905/proprietary/lib/libril.so:lib/libril.so \
    vendor/sony/c1905/proprietary/lib/libril-qcril-hook-oem.so:lib/libril-qcril-hook-oem.so \
    vendor/sony/c1905/proprietary/lib/libqmi_csi.so:lib/libqmi_csi.so \
    vendor/sony/c1905/proprietary/lib/libmmjpeg.so:lib/libmmjpeg.so \
    vendor/sony/c1905/proprietary/lib/libqmi_cci.so:lib/libqmi_cci.so \
    vendor/sony/c1905/proprietary/lib/libsurround_proc.so:lib/libsurround_proc.so \
    vendor/sony/c1905/proprietary/lib/libnetmgr.so:lib/libnetmgr.so \
    vendor/sony/c1905/proprietary/lib/libadsprpc.so:lib/libadsprpc.so \
    vendor/sony/c1905/proprietary/lib/libdl.so:lib/libdl.so \
    vendor/sony/c1905/proprietary/lib/libta.so:lib/libta.so \
    vendor/sony/c1905/proprietary/lib/libkeyctrl.so:lib/libkeyctrl.so \
    vendor/sony/c1905/proprietary/lib/libdsi_netctrl.so:lib/libdsi_netctrl.so \
    vendor/sony/c1905/proprietary/lib/libmmcamera_interface2.so:lib/libmmcamera_interface2.so \
    vendor/sony/c1905/proprietary/lib/libmorpho_denoiser.so:lib/libmorpho_denoiser.so \
    vendor/sony/c1905/proprietary/lib/libmmstillomx.so:lib/libmmstillomx.so \
    vendor/sony/c1905/proprietary/lib/libril-qc-qmi-1.so:lib/libril-qc-qmi-1.so \
    vendor/sony/c1905/proprietary/lib/libface.so:lib/libface.so \
    vendor/sony/c1905/proprietary/lib/libaudcal.so:lib/libaudcal.so \
    vendor/sony/c1905/proprietary/lib/libmmcamera_tintless_algo.so:lib/libmmcamera_tintless_algo.so \
    vendor/sony/c1905/proprietary/lib/libgsl.so:lib/libgsl.so \
    vendor/sony/c1905/proprietary/lib/libimage-omx-common.so:lib/libimage-omx-common.so \
    vendor/sony/c1905/proprietary/lib/libloc_adapter.so:system/lib/libloc_adapter.so \
    vendor/sony/c1905/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
    vendor/sony/c1905/proprietary/lib/libloc_eng.so:system/lib/libloc_eng.so \
    vendor/sony/c1905/proprietary/lib/libmercury.so:lib/libmercury.so \
    vendor/sony/c1905/proprietary/lib/libmm-abl.so:lib/libmm-abl.so \
    vendor/sony/c1905/proprietary/lib/librmp.so:lib/librmp.so \
    vendor/sony/c1905/proprietary/lib/libmmjpeg_interface.so:lib/libmmjpeg_interface.so \
    vendor/sony/c1905/proprietary/lib/libmmcamera_statsproc31.so:lib/libmmcamera_statsproc31.so \
    vendor/sony/c1905/proprietary/etc/firmware/dxhdcp2.b00:etc/firmware/dxhdcp2.b00 \
    vendor/sony/c1905/proprietary/etc/firmware/dxhdcp2.b01:etc/firmware/dxhdcp2.b01 \
    vendor/sony/c1905/proprietary/etc/firmware/dxhdcp2.b02:etc/firmware/dxhdcp2.b02 \
    vendor/sony/c1905/proprietary/etc/firmware/dxhdcp2.b03:etc/firmware/dxhdcp2.b03 \
    vendor/sony/c1905/proprietary/etc/firmware/dxhdcp2.mdt:etc/firmware/dxhdcp2.mdt \
    vendor/sony/c1905/proprietary/etc/firmware/dxhdcp2.flist:etc/firmware/dxhdcp2.flist \
    vendor/sony/c1905/proprietary/etc/firmware/vidc.mdt:etc/firmware/vidc.mdt \
    vendor/sony/c1905/proprietary/etc/firmware/tzlibasb.mdt:etc/firmware/tzlibasb.mdt \
    vendor/sony/c1905/proprietary/etc/firmware/tzlibasb.b02:etc/firmware/tzlibasb.b02 \
    vendor/sony/c1905/proprietary/etc/firmware/tzsuntory.b01:etc/firmware/tzsuntory.b01 \
    vendor/sony/c1905/proprietary/etc/firmware/a300_pm4.fw:etc/firmware/a300_pm4.fw \
    vendor/sony/c1905/proprietary/etc/firmware/vidcfw.elf:etc/firmware/vidcfw.elf \
    vendor/sony/c1905/proprietary/etc/firmware/tzlibasb.flist:etc/firmware/tzlibasb.flist \
    vendor/sony/c1905/proprietary/etc/firmware/tzsuntory.b00:etc/firmware/tzsuntory.b00 \
    vendor/sony/c1905/proprietary/etc/firmware/a225_pfp.fw:etc/firmware/a225_pfp.fw \
    vendor/sony/c1905/proprietary/etc/firmware/tzlibasb.b01:etc/firmware/tzlibasb.b01 \
    vendor/sony/c1905/proprietary/etc/firmware/vidc_1080p.fw:etc/firmware/vidc_1080p.fw \
    vendor/sony/c1905/proprietary/etc/firmware/a300_pfp.fw:etc/firmware/a300_pfp.fw \
    vendor/sony/c1905/proprietary/etc/firmware/vidc.b00:etc/firmware/vidc.b00 \
    vendor/sony/c1905/proprietary/etc/firmware/tzsuntory.mdt:etc/firmware/tzsuntory.mdt \
    vendor/sony/c1905/proprietary/etc/firmware/leia_pm4_470.fw:etc/firmware/leia_pm4_470.fw \
    vendor/sony/c1905/proprietary/etc/firmware/cyttsp_8064_mtp.hex:etc/firmware/cyttsp_8064_mtp.hex \
    vendor/sony/c1905/proprietary/etc/firmware/a225p5_pm4.fw:etc/firmware/a225p5_pm4.fw \
    vendor/sony/c1905/proprietary/etc/firmware/vidc.b02:etc/firmware/vidc.b02 \
    vendor/sony/c1905/proprietary/etc/firmware/vidc.b03:etc/firmware/vidc.b03 \
    vendor/sony/c1905/proprietary/etc/firmware/a225_pm4.fw:etc/firmware/a225_pm4.fw \
    vendor/sony/c1905/proprietary/etc/firmware/cyttsp_8960_cdp.hex:etc/firmware/cyttsp_8960_cdp.hex \
    vendor/sony/c1905/proprietary/etc/firmware/tzsuntory.b02:etc/firmware/tzsuntory.b02 \
    vendor/sony/c1905/proprietary/etc/firmware/tzsuntory.b03:etc/firmware/tzsuntory.b03 \
    vendor/sony/c1905/proprietary/etc/firmware/leia_pfp_470.fw:etc/firmware/leia_pfp_470.fw \
    vendor/sony/c1905/proprietary/etc/firmware/tzsuntory.flist:etc/firmware/tzsuntory.flist \
    vendor/sony/c1905/proprietary/etc/firmware/tzlibasb.b03:etc/firmware/tzlibasb.b03 \
    vendor/sony/c1905/proprietary/etc/firmware/tzlibasb.b00:etc/firmware/tzlibasb.b00 \
    vendor/sony/c1905/proprietary/etc/firmware/vidc.b01:etc/firmware/vidc.b01 \
    vendor/sony/c1905/proprietary/bin/hci_qcomm_init:bin/hci_qcomm_init \
    vendor/sony/c1905/proprietary/bin/qseecomd:bin/qseecomd \
    vendor/sony/c1905/proprietary/bin/netmgrd:bin/netmgrd \
    vendor/sony/c1905/proprietary/bin/efsks:bin/efsks \
    vendor/sony/c1905/proprietary/bin/qmuxd:bin/qmuxd \
    vendor/sony/c1905/proprietary/bin/qrngd:bin/qrngd \
    vendor/sony/c1905/proprietary/bin/updatemiscta:bin/updatemiscta \
    vendor/sony/c1905/proprietary/bin/mpdecision:bin/mpdecision \
    vendor/sony/c1905/proprietary/bin/rild:bin/rild \
    vendor/sony/c1905/proprietary/bin/thermald:bin/thermald \
    vendor/sony/c1905/proprietary/bin/taimport:bin/taimport \
    vendor/sony/c1905/proprietary/bin/ta_qmi_service:bin/ta_qmi_service \
    vendor/sony/c1905/proprietary/bin/mm-qcamera-daemon:bin/mm-qcamera-daemon \
    vendor/sony/c1905/proprietary/bin/ks:bin/ks \
    vendor/sony/c1905/proprietary/bin/rmt_storage:bin/rmt_storage \
    vendor/sony/c1905/proprietary/bin/led_deamon:bin/led_deamon
